import numpy as np
a = np.array([1,2,3,4,5])
b = np.array([10,20,30,40,50])
print("Add : ",np.add(a,b))
print("Array :  a is : ",a)
print("Array b is : ",b)
print("All are non - zero elements : ",np.all(a))
print("Greater : ",np.greater(a,b))
print("Grete equal : ",np.greater_equal(a,b))
print("Less : ",np.less(a,b))
print("Less equla : ",np.less_equal(a,b))
print("Equal : ",np.equal(a,[1,2,3,4,5]))
print("a close to b : ",np.allclose(a,[1,2,3,4,5]))
print("Zeros : ",np.zeros(4))
print("Ones : ",np.ones(4))
print("Linspace : ",np.linspace(0,1,5))
print("Array to list : ",a.tolist())
